pipeline {
    agent any

    parameters {
        booleanParam(name: 'RC', defaultValue: false, description: 'Is this a Release Candidate?')
    }
    
    environment {
        VERSION = "0.1.0"        
        VERSION_RC = "rc.2"
    }
    stages {
        stage('Audit tools') {                        
            steps {
                sh '''
                  git version
                  ./mvnw -version
                  java -version
                '''
            }
        }
        stage('Compile') {
            steps {
              echo "Building version: ${VERSION} with suffix: ${VERSION_RC}"
              sh './mvnw compile -Dcheckstyle.skip'
            }
        }
        stage('Unit Test') {
            steps {
              sh './mvnw test -Dcheckstyle.skip'
              junit 'target/surefire-reports/*.xml'
            }
        }
        stage('Package') {
            when {
                expression { return params.RC }
            } 
            steps {
              sh './mvnw package -Dcheckstyle.skip'
              archiveArtifacts artifacts: 'target/*.jar', followSymlinks: false
            }
        }
    }
}