pipeline {
    agent any
    environment {
        VERSION = "0.1.0"        
        VERSION_RC = "rc.2"
    }
    stages {
        stage('Audit tools') {                        
            steps {
                sh '''
                  git version
                  mvn -version
                  java -version
                '''
            }
        }
        stage('Compile') {
            steps {
              echo "Building version: ${VERSION} with suffix: ${VERSION_RC}"
              sh './mvnw compile'
            }
        }
        stage('Unit Test') {
            steps {
              sh './mvnw test'
              junit 'target/surefire-reports/*.xml'
            }
        }
        stage('Package') {
            steps {
              sh './mvnw package'
            }
        }
        stage('Archive Artifacts') {
            steps {
              archiveArtifacts artifacts: 'target/*.jar', followSymlinks: false
            }
        }
    }
}